#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

hour=0
mnts=0
while [ $hour -lt 13 ]
do
    mnts=1
    echo "Hour : $hour"
    while [ $mnts -lt 60 ]
    do
        echo "$mnts"
        mnts=$(( mnts + 1))
    done
    hour=$(( hour + 1 ))
done